# ---------------------------------------------------------------------------------------------------------------------
# Batch
# ---------------------------------------------------------------------------------------------------------------------
Batch:
  Metric alert rules should be configured on Batch accounts:
    effect: Audit # AuditIfNotExists, Disabled
    metricName: # no default parameters

# ---------------------------------------------------------------------------------------------------------------------
# Compute
# ---------------------------------------------------------------------------------------------------------------------
Compute:
  Allowed virtual machine size SKUs:
    listOfAllowedSKUs: []

  Managed disks should use a specific set of disk encryption sets for the customer-managed key encryption:
    effect: # Audit, Deny, Disabled
    allowedEncryptionSets: []

  Only approved VM extensions should be installed:
    effect: Audit # Audit, Deny, Disabled
    approvedExtensions: []

  Resource logs in Virtual Machine Scale Sets should be enabled:
    effect: AuditIfNotExists # AuditIfNotExists, Disabled
    includeAKSClusters: # True/False

# ---------------------------------------------------------------------------------------------------------------------
# Cosmos DB
#
# ---------------------------------------------------------------------------------------------------------------------
Cosmos DB:
  Azure Cosmos DB allowed locations:
    listOfAllowedLocations: []
    policyEffect: deny # deny, audit, disabled

  Azure Cosmos DB throughput should be limited:
    throughputMax:
    effect: # audit, deny, disabled

# ---------------------------------------------------------------------------------------------------------------------
# Data Factory
# ---------------------------------------------------------------------------------------------------------------------

Data Factory:
  "[Preview]: Azure Data Factory linked service resource type should be in allow list":
    effect: Audit # Audit, Deny, Disabled
    allowedLinkedServiceResourceTypes: # AdlsGen2CosmosStructuredStream, AdobeExperiencePlatform, AdobeIntegration, AmazonRedshift, AmazonS3, AzureBlobFS, AzureBlobStorage, AzureDataExplorer, AzureDataLakeStore, AzureDataLakeStoreCosmosStructuredStream, AzureDataShare, AzureFileStorage, AzureKeyVault, AzureMariaDB, AzureMySql, AzurePostgreSql, AzureSearch, AzureSqlDatabase, AzureSqlDW, AzureSqlMI, AzureTableStorage, Cassandra, CommonDataServiceForApps, CosmosDb, CosmosDbMongoDbApi, Db2, DynamicsCrm, FileServer, FtpServer, GitHub, GoogleCloudStorage, Hdfs, Hive, HttpServer, Informix, Kusto, MicrosoftAccess, MySql, Netezza, Odata, Odbc, Office365, Oracle, PostgreSql, Salesforce, SalesforceServiceCloud, SapBw, SapHana, SapOpenHub, SapTable, Sftp, SharePointOnlineList, Snowflake, SqlServer, Sybase, Teradata, HDInsightOnDemand, HDInsight, AzureDataLakeAnalytics, AzureBatch, AzureFunction, AzureML, AzureMLService, MongoDb, GoogleBigQuery, Impala, ServiceNow, Dynamics, AzureDatabricks, AmazonMWS, SapCloudForCustomer, SapEcc, Web, MongoDbAtlas, HBase, Spark, Phoenix, PayPal, Marketo, Responsys, SalesforceMarketingCloud, Presto, Square, Xero, Jira, Magento, Shopify, Concur, Hubspot, Zoho, Eloqua, QuickBooks, Couchbase, Drill, Greenplum, MariaDB, Vertica, MongoDbV2, OracleServiceCloud, GoogleAdWords, RestService, DynamicsAX, AzureDataCatalog, AzureDatabricksDeltaLake


# ---------------------------------------------------------------------------------------------------------------------
# General
# ---------------------------------------------------------------------------------------------------------------------
General:
  Allowed locations:
    listOfAllowedLocations: []

  Allowed locations for resource groups:
    listOfAllowedLocations: []

  Allowed resource types:
    listOfResourceTypesAllowed: []

  Not allowed resource types:
    effect: Deny # Audit, Deny, Disabled
    listOfResourceTypesNotAllowed: []

# ---------------------------------------------------------------------------------------------------------------------
# Guest Configuration
# ---------------------------------------------------------------------------------------------------------------------
Guest Configuration:
  Audit Windows machines that are not set to the specified time zone:
    TimeZone: "(UTC-08:00) Pacific Time (US & Canada)"

  # c633f6a2-7f8b-4d9e-9456-02f0f04f5505
#Guest Configuration:
#  "Audit Linux machines that don't have the specified applications installed"
#  "Audit Linux machines that have the specified applications installed"
#  "Audit Windows machines missing any of specified members in the Administrators group"
#  "Audit Windows machines network connectivity"
#  "Audit Windows machines on which the Log Analytics agent is not connected as expected"
#  "Audit Windows machines on which the specified services are not installed and 'Running'"
#  "Audit Windows machines that are not joined to the specified domain"
#  "Audit Windows machines that are not set to the specified time zone"
#  "Audit Windows machines that contain certificates expiring within the specified number of days"
#  "Audit Windows machines that do not contain the specified certificates in Trusted Root"
#  "Audit Windows machines that do not have the specified Windows PowerShell execution policy"
#  "Audit Windows machines that do not have the specified Windows PowerShell modules installed"
#  "Audit Windows machines that don't have the specified applications installed"
#  "Audit Windows machines that have the specified applications installed"
#  "Audit Windows machines that have the specified members in the Administrators group"
#
## ---------------------------------------------------------------------------------------------------------------------
## Key Vault
## ---------------------------------------------------------------------------------------------------------------------
Key Vault:
  Certificates using RSA cryptography should have the specified minimum key size:
    minimumRSAKeySize: 2048
#  "[Preview]: Certificates should be issued by the specified non-integrated certificate authority"
#  "[Preview]: Certificates should have the specified lifetime action triggers"
#  "[Preview]: Certificates should not expire within the specified number of days"
#  "[Preview]: Certificates using RSA cryptography should have the specified minimum key size"
#  "[Preview]: Keys should have more than the specified number of days before expiration"
#  "[Preview]: Keys should have the specified maximum validity period"
#  "[Preview]: Keys should not be active for longer than the specified number of days"
#  "[Preview]: Keys using RSA cryptography should have a specified minimum key size"
#  "[Preview]: Secrets should have more than the specified number of days before expiration"
#  "[Preview]: Secrets should have the specified maximum validity period"
#  "[Preview]: Secrets should not be active for longer than the specified number of days"
#
## ---------------------------------------------------------------------------------------------------------------------
## Kubernetes
## ---------------------------------------------------------------------------------------------------------------------
#Kubernetes:
#  "Kubernetes cluster containers CPU and memory resource limits should not exceed the specified limits"
#  "Kubernetes cluster containers should not share host process ID or host IPC namespace"
#  "Kubernetes cluster containers should not use forbidden sysctl interfaces"
#  "Kubernetes cluster containers should only listen on allowed ports"
#  "Kubernetes cluster containers should only use allowed AppArmor profiles"
#  "Kubernetes cluster containers should only use allowed ProcMountType"
#  "Kubernetes cluster containers should only use allowed capabilities"
#  "Kubernetes cluster containers should only use allowed images"
#  "Kubernetes cluster containers should only use allowed seccomp profiles"
#  "Kubernetes cluster containers should run with a read only root file system"
#  "Kubernetes cluster pod FlexVolume volumes should only use allowed drivers"
#  "Kubernetes cluster pod hostPath volumes should only use allowed host paths"
#  "Kubernetes cluster pods and containers should only run with approved user and group IDs"
#  "Kubernetes cluster pods and containers should only use allowed SELinux options"
#  "Kubernetes cluster pods should only use allowed volume types"
#  "Kubernetes cluster pods should only use approved host network and port range"
#  "Kubernetes cluster pods should use specified labels"
#  "Kubernetes cluster services should listen only on allowed ports"
#  "Kubernetes cluster should not allow privileged containers"
#  "Kubernetes clusters should be accessible only over HTTPS"
#  "Kubernetes clusters should not allow container privilege escalation"
#  "Kubernetes clusters should use internal load balancers"
#  "[Preview]: Kubernetes cluster services should only use allowed external IPs"
#  "[Preview]: Kubernetes clusters should disable automounting API credentials"
#  "[Preview]: Kubernetes clusters should not grant CAP_SYS_ADMIN security capabilities"
#  "[Preview]: Kubernetes clusters should not use specific security capabilities"
#  "[Preview]: Kubernetes clusters should not use the default namespace"
#
## ---------------------------------------------------------------------------------------------------------------------
## Lighthouse
## ---------------------------------------------------------------------------------------------------------------------
#Lighthouse:
#  "Allow managing tenant ids to onboard through Azure Lighthouse"
#
## ---------------------------------------------------------------------------------------------------------------------
## Machine Learning
## ---------------------------------------------------------------------------------------------------------------------
#Machine Learning:
#  "[Preview]: Configure allowed Python packages for specified Azure Machine Learning computes"
#  "[Preview]: Configure allowed module authors for specified Azure Machine Learning computes"
#  "[Preview]: Configure allowed registries for specified Azure Machine Learning computes"
#  "[Preview]: Configure an approval endpoint called prior to jobs running for specified Azure Machine Learning computes"
#  "[Preview]: Configure code signing for training code for specified Azure Machine Learning computes"
#  "[Preview]: Configure log filter expressions and datastore to be used for full logs for specified Azure Machine Learning computes"
#
## ---------------------------------------------------------------------------------------------------------------------
## Monitoring
## ---------------------------------------------------------------------------------------------------------------------
#Monitoring:
#  "An activity log alert should exist for specific Administrative operations"
#  "An activity log alert should exist for specific Policy operations"
#  "An activity log alert should exist for specific Security operations"
#  "Audit Log Analytics workspace for VM - Report Mismatch"
#  "Audit diagnostic setting"
#  "Dependency agent should be enabled for listed virtual machine images"
#  "Dependency agent should be enabled in virtual machine scale sets for listed virtual machine images"
#  "Log Analytics agent should be enabled in virtual machine scale sets for listed virtual machine images"
#  "[Preview]: Log Analytics Agent should be enabled for listed virtual machine images"
#
## ---------------------------------------------------------------------------------------------------------------------
## Network
## ---------------------------------------------------------------------------------------------------------------------
#Network:
#  "A custom IPsec/IKE policy must be applied to all Azure virtual network gateway connections"
#  "Network Watcher should be enabled"
#  "Virtual machines should be connected to an approved virtual network"
#  "Virtual networks should use specified virtual network gateway"
#
## ---------------------------------------------------------------------------------------------------------------------
## SQL
## ---------------------------------------------------------------------------------------------------------------------
#SQL:
#  "Virtual network firewall rule on Azure SQL Database should be enabled to allow traffic from the specified subnet"
#
## ---------------------------------------------------------------------------------------------------------------------
## Storage
## ---------------------------------------------------------------------------------------------------------------------
#Storage:
#  "Storage accounts should be limited by allowed SKUs"
#
## ---------------------------------------------------------------------------------------------------------------------
## Synapse
## ---------------------------------------------------------------------------------------------------------------------
#Synapse:
#  "Synapse managed private endpoints should only connect to resources in approved Azure Active Directory tenants"
#
## ---------------------------------------------------------------------------------------------------------------------
## Tags
## ---------------------------------------------------------------------------------------------------------------------
#Tags:
#  "Require a tag and its value on resource groups"
#  "Require a tag and its value on resources"
#  "Require a tag on resource groups"
#  "Require a tag on resources"
