# ---------------------------------------------------------------------------------------------------------------------
# API Management
# ---------------------------------------------------------------------------------------------------------------------
API Management:
  API Management service should use a SKU that supports virtual networks:
    effect: Deny # Audit, Deny, Disabled. Default: Audit
    listOfAllowedSKUs: # Developer, Basic, Standard, Premium, Isolated, Consumption
      - Developer
      - Premium
      - Isolated

Kubernetes:
  Kubernetes cluster containers CPU and memory resource limits should not exceed the specified limits:
    effect: Audit # Audit, Deny, Disabled
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - azure-arc
    namespaces: []
    labelSelector: {}
    cpuLimit: "200m"
    memoryLimit: "1Gi"
  Kubernetes cluster containers should not share host process ID or host IPC namespace:
    effect: Audit # Audit, Deny, Disabled
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - azure-arc
    namespaces: [ ]
    labelSelector: {}
  Kubernetes cluster containers should not use forbidden sysctl interfaces:
    effect: Audit # Audit, Deny, Disabled
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - azure-arc
    namespaces: [ ]
    labelSelector: {}
    forbiddenSysctls: [ ]
#  Kubernetes cluster containers should only listen on allowed ports
#  Kubernetes cluster containers should only use allowed AppArmor profiles
#  Kubernetes cluster containers should only use allowed ProcMountType
#  Kubernetes cluster containers should only use allowed capabilities
#  Kubernetes cluster containers should only use allowed images
#  Kubernetes cluster containers should only use allowed seccomp profiles
#  Kubernetes cluster containers should run with a read only root file system
#  Kubernetes cluster pod FlexVolume volumes should only use allowed drivers
#  Kubernetes cluster pod hostPath volumes should only use allowed host paths
#  Kubernetes cluster pods and containers should only run with approved user and group
#    IDs
#  Kubernetes cluster pods and containers should only use allowed SELinux options
#  Kubernetes cluster pods should only use allowed volume types
#  Kubernetes cluster pods should only use approved host network and port range
#  Kubernetes cluster pods should use specified labels
#  Kubernetes cluster services should listen only on allowed ports
#  Kubernetes cluster should not allow privileged containers
#  Kubernetes clusters should be accessible only over HTTPS
#  Kubernetes clusters should not allow container privilege escalation
#  Kubernetes clusters should use internal load balancers
#  '[Preview]: Kubernetes cluster services should only use allowed external IPs'
#  '[Preview]: Kubernetes clusters should disable automounting API credentials'
#  '[Preview]: Kubernetes clusters should not grant CAP_SYS_ADMIN security capabilities'
#  '[Preview]: Kubernetes clusters should not use specific security capabilities'
#  '[Preview]: Kubernetes clusters should not use the default namespace'